apiVersion: v1
kind: Pod
metadata:
  name: alpine-latest
spec:
  schedulerName: layer-scheduler
  containers:
  - name: alpine-latest
    image: http://172.16.115.132:5000/v2/alpine:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 400Mi
