apiVersion: v1
kind: Pod
metadata:
  name: coredns-v1-8-6
spec:
  schedulerName: layer-scheduler
  containers:
  - name: coredns-v1-8-6
    image: http://172.16.115.132:5000/v2/coredns:v1.8.6
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 400Mi