apiVersion: v1
kind: Pod
metadata:
  name: coredns_v1.8.6
spec:
  schedulerName: layer-scheduler
  containers:
  - name: coredns_v1.8.6
    image: http://localhost:5000/v2/coredns:v1.8.6
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 400Mi