apiVersion: v1
kind: Pod
metadata:
  name: mysql-5.7
spec:
  schedulerName: layer-scheduler
  containers:
  - name: mysql-5.7
    image: http://172.16.115.132:5000/v2/mysql:5.7
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 400Mi